server:
  port: 8182
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  application:
    name: resource-server2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka