server:
  port: 8181
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  application:
    name: resource-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka