server:
  port: 8100
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  application:
    name: microservice-job
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka